### ISSUE TITLE
How to use this library in swift? 

### ISSUE THREAD

**Issue by varalakshmi090** [Yalantis/Context-Menu.iOS#38]
Hi all,

I am new for developing the ios application. I have started to use this library. But I have used swift 2.0. In documentation  don't have more details using of swift. can any one explain with examples.

**Comment by IgorMuzyka** [comment]
Hi @varalakshmi090.
Be sure to have latest version of **cocoapods** and install library using them.
And then you can follow this [stackoverflow answer](http://stackoverflow.com/questions/24122914/how-to-integrate-cocoapods-with-a-swift-project)
Also it's a good idea to use newer version of **Swift**( since it will not require you to use *bridging header) file.
Please respond or close issue if this was or was not helpful for you.

**Comment by varalakshmi090** [comment]
Thanks @IgorMuzyka.
Then How can I call the objects with use of swift. can you give some sample examples for that library.
